name: CI
on: [push, pull_request]

jobs:
  # shellcheck:
  #   name: ShellCheck
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Run ShellCheck
  #       uses: ludeeus/action-shellcheck@master
  #       with:
  #         # This tells it specifically to check your script file
  #         additional_files: 'dockctl' 

  test:
    runs-on: ubuntu-latest
    name: Install Bats and bats libs
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Setup Bats and bats libs
      id: setup-bats
      uses: bats-core/bats-action@4.0.0
